In [1]:
# import packages and data set MNIST
import tensorflow as tf
tf.enable_eager_execution()
import numpy as np

mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [2]:
# build the NN model

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [3]:
# Display the single returned class
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.7219994 ,  0.03851923, -0.60796845, -0.34495887,  0.26929867,
         0.16979468, -0.35175967, -0.16407262,  0.17893612, -0.1404448 ]],
      dtype=float32)

In [4]:
# use softmax to transfer the logits into probability
tf.nn.softmax(predictions).numpy()

array([[0.19677013, 0.09934077, 0.05204289, 0.06769943, 0.12512776,
        0.11327647, 0.06724059, 0.08112281, 0.11431672, 0.08306238]],
      dtype=float32)

In [5]:
# define the loss func
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [6]:
loss_fn(y_train[:1], predictions).numpy()

2.1779237

In [7]:
# compile the model, -> define the optimizer, feed the loss func, and define the model evaluate criterien
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [8]:
# fit/ train the model -> in order to configure the parameters, minimizing the loss.
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
60000/60000 [==============================] - 3s 50us/sample - loss: 0.2948 - acc: 0.9148
Epoch 2/5
60000/60000 [==============================] - 3s 45us/sample - loss: 0.1431 - acc: 0.9573
Epoch 3/5
60000/60000 [==============================] - 3s 45us/sample - loss: 0.1058 - acc: 0.9685
Epoch 4/5
60000/60000 [==============================] - 3s 45us/sample - loss: 0.0878 - acc: 0.9730
Epoch 5/5
60000/60000 [==============================] - 3s 45us/sample - loss: 0.0731 - acc: 0.9774


In [9]:
# Use Validation / Test set to evaluate the model
model.evaluate(x_test,  y_test, verbose=2)

10000/10000 - 0s - loss: 0.0766 - acc: 0.9751


[0.07663739976426587, 0.9751]

In [10]:
# Package the model together with the softmax layer

probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [11]:
# show the final results

probability_model(x_test[:5])

<tf.Tensor: id=68333, shape=(5, 10), dtype=float32, numpy=
array([[1.5531460e-06, 2.5046745e-07, 1.9844194e-06, 7.0399656e-05,
        2.8205790e-10, 1.8713153e-07, 2.4250389e-14, 9.9989891e-01,
        3.6211031e-07, 2.6370808e-05],
       [1.8677030e-08, 5.1606917e-06, 9.9999380e-01, 9.0137161e-07,
        4.0444400e-17, 1.3394269e-07, 1.5680325e-10, 1.3694128e-15,
        4.6981166e-09, 2.8250163e-16],
       [4.4752802e-08, 9.9905032e-01, 3.8032624e-05, 4.4858389e-06,
        7.7471879e-05, 2.5960620e-05, 1.5316053e-05, 5.8905332e-04,
        1.9882663e-04, 5.3772777e-07],
       [9.9988639e-01, 3.1266234e-09, 8.7694093e-07, 1.7761002e-07,
        1.5748700e-08, 2.1814596e-07, 1.1242028e-07, 3.1552692e-05,
        5.5064135e-09, 8.0610662e-05],
       [1.5736706e-06, 1.2730671e-08, 6.7970022e-06, 1.3662712e-07,
        9.5674980e-01, 2.7339905e-07, 6.1755372e-07, 1.8178146e-04,
        3.7232958e-06, 4.3055322e-02]], dtype=float32)>